### ISSUE TITLE
Bitbang SPI phase=1 lowest bit is wrong

### ISSUE THREAD

**Issue by gingle** [adafruit/Adafruit_CircuitPython_BitbangIO#20]
### CircuitPython version

```python
Adafruit CircuitPython 6.1.0 on 2021-01-21; Adafruit QT Py M0 with samd21e18 also
Adafruit CircuitPython 7.0.0-beta.0-161-g65753a1c2 on 2021-09-01; with samd51j19
```

### Code/REPL

```python
# 09/03/2021
# looses both least significant bits
# tested on QT Py and Metro_M4_Express

import board
import digitalio
import adafruit_bitbangio as bitbangio


nEN = digitalio.DigitalInOut(board.A1)    
nEN.direction = digitalio.Direction.OUTPUT

spi = bitbangio.SPI(board.SCK, MOSI=board.MOSI, MISO=board.MISO)

def TestSPI():  
    select = nEN
    select.value = True
    while not spi.try_lock():
        pass
    spi.configure(baudrate=100000, polarity=0, phase=1, bits=8 )
    bytes_read = bytearray(4)
    select.value = False
    bytes_read = bytearray([0x33])  # changes 0x33 to 0x32 
    spi.write(bytes_read)
    bytes_read = bytearray([0x0b])  # changes 0x0b to 0x0a
    spi.write(bytes_read)
    select.value = True
    spi.unlock()
```

### Behavior

![image](https://user-images.githubusercontent.com/7987362/132258730-fa61428c-f88a-49b6-96c3-881f4726fde1.png)

### Additional information

This works correctly:
from adafruit_bus_device.spi_device import SPIDevice

**Comment by dhalbert** [comment]
Transferred to https://github.com/adafruit/Adafruit_CircuitPython_BitbangIO/

**Comment by gingle** [comment]
Dan, you are correct. I verified the built in version of bitbangio as working correctly. the Adafruit version has the LSbit problem.

**Comment by Linkeor** [comment]
Bonjour,
I don't think I'm in the wrong place. I had to test a max31856 and a tft st7735R with bitbangio, on a pico/u2if. I can read but not write in the registers, or at least the values that come out of the register are not at all those written and of course my temperatures are wrong and the screen displays nothing.
After exploring and testing a lot of things I modified def write( in adafruit_bitbangio.py and everything now works (for the max31856 in phase 1 as for the st7735 in phase 0)
This happens on lines 401 and 407 where
401
`                    self._sclk.value = self._polarity`
becomes
`                    self._sclk.value = not self._polarity`
and 407 
`                    self._sclk.value = not self._polarity`
becomes
`                    self._sclk.value =  self._polarity`

I don't know if this is the best way to do things and if it could have side effects, I'm not an experienced developer. But for now this is a modification that works for me.
I hope this can help.

PS sorry, for English via google translate, I read well but I speak English "like a Frenchman" ;-)

**Comment by chipgarner** [comment]
Please accept @Linkeor 's pull request as above! The MAX31956 does not work using BitbangIO without this fix. Some kiln-controller users (https://github.com/jbruce12000/kiln-controller) cannot upgrade their software without re-soldering as software pins will not work with this library on the '56.

I have tested @Linkeor  's changes on an RPi 3+ with both the MAX31855 and '56. They work in all the expected cases, hardware pins / software SPI via BitbangIO, hardware pins / hardware SPI, software pins / BitbangIO.

This change does not effect the MAX31855 but it seems to be needed for any board that uses MOSI.

**Comment by kbsriram** [comment]
While writing some tests, I came across what might be a timing bug introduced by https://github.com/adafruit/Adafruit_CircuitPython_BitbangIO/pull/30

This is the test code:
```python
    with adafruit_bitbangio.SPI(clock=clock, MOSI=copi, MISO=cipo) as spi:
        spi.try_lock()
        spi.configure(baudrate=100, polarity=0, phase=0, bits=8)
        echo.enable(True)
        spi.write([0b10101011])
```

Prior to the change, as noted in the initial description here, there was a general offset problem where bits were pushed out one clock transition too late. However, each bit was still pushed on the data line at the right clock phase.

Here is a sample trace **before** the fix. The first bit is set on the first falling clock, but the first _rising_ clock has already been read by that time. So the peripheral effectively sees a right-rotated version of the data in this case. However, each bit is still pushed during the falling clock transition, it doesn't interfere with the read.

![mode_0_prev](https://github.com/adafruit/Adafruit_CircuitPython_BitbangIO/assets/1495065/6dffb330-4f32-445e-b68b-53098d7bbce0)

However, **after** the fix the bits are set on _rising_ clock transitions, when they are also read.

![mode_0_after](https://github.com/adafruit/Adafruit_CircuitPython_BitbangIO/assets/1495065/de23d7ec-5a12-4d36-b648-af0775e6f2b7)

Possibly many peripherals are still able to decode it as there's _just_ enough delay between the data line being set and the clock being immediately transitioned in python land; but I'm not sure if this is ideal.

(Happy to provide a fix if this seems worth correcting, as I noticed this while testing the protocol; rather than seeing issues in the wild.)
